[build]
  publish = "."  # This should be the directory where your index.html is located
  # command = "npm run build"  # Uncomment if you have a build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200